
- replace:
    path: '{{ repository_root_directory }}/tools/commons/commons.conf'
    regexp: '^\s*number-of-streams = .*$'
    replace: '        number-of-streams = {{ streams }}'
  when: streams is defined
